### ISSUE TITLE
symbols= parameter doesn't work with compressed revisions ($wgCompressRevisions = true)

### ISSUE THREAD

**Issue by Xenareee** [edwardspec/mediawiki-extension-JsCalendar#7] opened 2023-03-05 17:59 UTC
This issue makes JsCalendar unusable/broken with the "symbols" parameter.

I mistakenly reported this bug on the Mediawiki Phabricator. I explained it in depth there, so to not repeat the same thing **here's the link to the report:**
[https://phabricator.wikimedia.org/T331228](https://phabricator.wikimedia.org/T331228)

**Comment by edwardspec** [comment] 2023-03-05 19:06
Not reproduced locally. Might be caused by one of the pages in the wiki having incorrect UTF-8 on it.

The error mentioned on https://phabricator.miraheze.org/T9688 is happening in MediaWiki parser (not in the JsCalendar code):
```
preg_match_all error 4: Malformed UTF-8 characters, possibly incorrectly encoded
from /srv/mediawiki/w/includes/MagicWordArray.php(319)
#0 /srv/mediawiki/w/includes/parser/Parser.php(4116): MagicWordArray->matchAndRemove(string)
#1 /srv/mediawiki/w/includes/parser/Parser.php(1636): Parser->handleDoubleUnderscore(string)
#2 /srv/mediawiki/w/includes/parser/Parser.php(882): Parser->internalParse(string, boolean, boolean)
#3 /srv/mediawiki/w/includes/parser/Parser.php(906): Parser->recursiveTagParse(string, boolean)
#4 /srv/mediawiki/w/extensions/JsCalendar/includes/EventCalendar.php(192): Parser->recursiveTagParseFully(string)
...
```

It's theoretically possible that the page had incorrect UTF-8 on it (JsCalendar passes contents of the page to MediaWiki parser),
but per what I see in the Phabricator, your page only had the word "Test" on it and nothing else (so it can't be incorrect UTF-8).

JsCalendar doesn't do any transformations to the "contents of the page" string before passing it to Parser. It's not truncated, not wrapped, not encoded, etc. JsCalendar takes the page text directly from the database and gives it to Parser.

**Comment by edwardspec** [comment] 2023-03-05 19:13
See https://phabricator.wikimedia.org/T321234
Closing, as this very same error happens without JsCalendar.

**Comment by bawolff** [comment] 2023-03-06 14:42
FWIW, to reiterate what i said on the other bug, I do not believe that this issue is the same as https://phabricator.wikimedia.org/T321234. https://phabricator.wikimedia.org/T321234 is about old non-utf8 valid data that for some reason was not normalized properly. Any page that this is happening on that is less than 15 years old, probably has a different cause (May or may not be this extensions fault, I'm not familiar with this extensions code. Could be some other issue at miraheze)

**Comment by bawolff** [comment] 2023-03-06 14:48
It may quite possibly be the fault of code at https://github.com/edwardspec/mediawiki-extension-JsCalendar/blob/master/includes/FindEventPagesQuery.php#L188 - this is not processing the old_flags field properly, which could result in the exception described depending on the wikis config (Processing old_flags properly is really hard, I would generally recommend using MW core's various classes to get page text  instead if at all possible)

**Comment by edwardspec** [comment] 2023-03-07 03:00
> this is not processing the old_flags field properly

Thank you.

Turns out, Miraheze had `$wgCompressRevisions = true;`, that's why it's not working. All revisions are compressed.
https://github.com/miraheze/mw-config/blob/7b230dd2072bb2361b099adba3ba17b9edcdaf33/Database.php

>  I would generally recommend using MW core's various classes to get page text instead

Will investigate. This seems to be handled in `SqlBlobStore::expandBlob()`, can also be done via `SqlBlobStore::getBlobBatch()`.

**Comment by edwardspec** [comment] 2023-03-07 11:26
Should be working now.

**Closed as completed by edwardspec** 2023-03-07 11:26 UTC
Labels: enhancement
